### ISSUE TITLE
Redis issue with kubernetes

### ISSUE THREAD

**Issue by ravipam** [luin/ioredis#1064]
I need to deploy nginx, web (angularjs), api (node.js) , redis using kubernetes. However, i am getting error with redis and api (node.js). 

```
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis redis:6379
at errnoException (dns.js:50:10)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

I tried multiple configuration but nothing worked.

```
const redis = new Redis('redis://redis:6379');
const redis = new Redis({ port: 6379, host: 'redis', connectTimeout: 10000 });
const client = redis.createClient(6379,"redis");
const redis = new Redis('ioredis'); 
```

I put all the containers in one deployment i.e, web, api, redis and then created the service using type: load balancer. I am able to access the application but i am getting the [ioredis] error in my api logs.

Kubernetes version: 1.15.7
Cloud being used: (aws) 
Installation method: kops
Host OS: ubuntu

**Deployment yaml**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app1
    env: prod
spec:
  selector:
    matchLabels:
      app: app1
      env: prod
  replicas: 3
  template:
    metadata:
      labels:
        app: app1
        env: prod
    spec:
      containers:
      - name: web-angular-nginx
        image: xxxx.dkr.ecr.us-east-1.amazonaws.com/web
        ports:
        - containerPort: 8080
      - name: api-nodejs
        image: xxxx.dkr.ecr.us-east-1.amazonaws.com/api
        ports:
        - containerPort: 7000
      - name: xxxx.dkr.ecr.us-east-1.amazonaws.com/redis
        image: redis
        ports:
        - containerPort: 6379
```

**Service yaml**

```
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: app1
spec:
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: app1
    env: prod
  type: LoadBalancer
```

**Docker-compose.yml (i am using docker-compose.yml to build images)**

```
version: '3'
services:
  redis:
    image: redis:latest
    build: redis
    container_name: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"
    volumes:
      - /app/redis.conf:/usr/local/etc/redis/redis.conf
  apiserver:
    build: api
    container_name: api
    environment:
     - NODE_ENV=stage
    links:
     - redis:redis
    ports:
     - 7000:7000
    volumes:
     - api_vol:/usr/src/app
  webserver:
    build: web
    container_name: web
    ports:
     - 80:80
    volumes:
     - webserver_vol:/usr/src/app
     - nginx_vol:/etc/nginx
volumes:
  api_vol:
  web_vol:
  nginx_vol:
```

Any ideas and suggestion to resolve the redis error. What is the best deployment strategy? 

Thanks
