### ISSUE TITLE
[ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.

### ISSUE THREAD

**Issue by jitenderchand** [luin/ioredis#1144]
I am trying to setup Redis cluster with apollo server. I am using docker to up my application and Redis is installed locally. The `RedisCache` is just working fine with apollo. However,  `RedisClusterCache` is throwing error. I have seen a similar bug has already been reported but the solution given is not working with my code.

My docker setup for Redis

```
redis:
    image: "bitnami/redis:latest"
    ports:
    - 6379
    environment:
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - redis-data:/bitnami

  redis-replica:
    image: "bitnami/redis:latest"
    ports:
    - "6379"
    depends_on:
    - redis
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis
      REDIS_MASTER_PORT_NUMBER: 6379
      ALLOW_EMPTY_PASSWORD: "yes"
```

Apollo Setup

```
const server = new ApolloServer({
        typeDefs,
        resolvers,
        cache: new RedisClusterCache([
                {
                    host: "redis",
                    port: 6379
                }
            ],
        ),
        plugins: [responseCachePlugin()],
        tracing: isDevelopmentEnvironment,
        dataSources: () => {
            return {
                movies: new MyMovies(),
                
            };
        }
    });
```

Error:

```
api_1    | [Node] [ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
api_1    | [Node]     at tryNode (/home/node/app/node_modules/ioredis/built/cluster/index.js:359:31)
api_1    | [Node]     at /home/node/app/node_modules/ioredis/built/cluster/index.js:376:21
api_1    | [Node]     at /home/node/app/node_modules/ioredis/built/cluster/index.js:624:24
api_1    | [Node]     at run (/home/node/app/node_modules/ioredis/built/utils/index.js:156:22)
api_1    | [Node]     at tryCatcher (/home/node/app/node_modules/standard-as-callback/built/utils.js:11:23)
api_1    | [Node]     at /home/node/app/node_modules/standard-as-callback/built/index.js:30:51
api_1    | [Node]     at runMicrotasks (<anonymous>)
api_1    | [Node]     at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

Version:

```
"apollo-datasource-rest": "^0.8.1",
"apollo-server-cache-redis": "^1.2.1",
"apollo-server-express": "^2.14.1",
"apollo-server-plugin-response-cache": "^0.5.2",

```
