### ISSUE TITLE
Usage with Twemproxy

### ISSUE THREAD

**Issue by NuSkooler** [luin/ioredis#284]
Is there an example somewhere of using iored with Twemproxy? I'm attempting to do so but connections are not succeeding. On the Twemproxy side, the log is spammed with errors about unsupported `client` commands.

My connection looks like this:
```
const options = {
		host			: TWEMPROXY_IP_ADDR,
		port			: TWEMPROXY_PORT,
		connectionName	: `myserver.${uuid.v4()}`,
		keyPrefix		: 'myprefix:',
		enableReadyCheck	: false,	//	cannot send INFO to twemproxy
	};
	
	redis = new Redis(options);
```

**Comment by NuSkooler** [comment]
My apologies -- it seems I can simply remove `connectionName` from options as this is causing `CLIENT SETNAME ...`

**Comment by luin** [comment]
I haven't used Twemproxy, but if it doesn't support `client` command, that's the problem.

**Comment by luin** [comment]
I'm closing this issue. Feel free to reopen it if you think the issue is still valid.

**Comment by tuananh** [comment]
@NuSkooler i tried removing connectionName and it seems to work so far. Do you have any other issue with Twemproxy and ioredis?

**Comment by NuSkooler** [comment]
@tuananh Simply removing `connectionName` does the trick for me - Twemproxy + ioredis working great!

**Comment by ciarans** [comment]
@NuSkooler I cant seem to get my twemproxy working, here is my Node code

```js
const client = new redis({
    host: "twemproxy",
    port: 7000,
    password: process.env.REDIS_RULES_PASSWORD,
    enableReadyCheck: false
});
```
Here is my yaml

```yml
leaf:
  listen: 127.0.0.1:7000
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  redis: true
  redis_auth: CrazyRedisAuthPassword
  server_retry_timeout: 1000
  server_failure_limit: 3
  servers:
   - redis-rules-slave-one:6379:1
   - redis-rules-slave-two:6378:2
   - emaster.amazonaws.com:6379:3
```

Any help would be appreciated
