### ISSUE TITLE
Command failed when a new redis instance online behind twemproxy

### ISSUE THREAD

**Issue by shaunxu** [luin/ioredis#573]
I'm trying to use ioredis with twemproxy. From other issues I knew that twemproxy doesn't support `INFO` command. So disabled `enableReadyCheck` in ioredis and it worked.

But when I killed one of my redis instance and restart it, ioredis reported an error when performing `SET` command against this instance. The error was

```
{ ReplyError: ERR Connection refused
    at JavascriptRedisParser.returnError (/Users/shaunxu/playground/redis-cluster-test-cli/node_modules/ioredis/lib/redis/parser.js:24:25)
    at JavascriptRedisParser.execute (/Users/shaunxu/playground/redis-cluster-test-cli/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/Users/shaunxu/playground/redis-cluster-test-cli/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:598:20)
  name: 'ReplyError',
  message: 'ERR Connection refused',
  command:
   { name: 'set',
     args:
      [ 'de2e29f3-e69f-4d20-8925-7a0f66ead7a3',
        'db6a92a3-408a-4651-869c-dbb5631d4db9' ] } }
```

I think this is because twemproxy began to route incoming command once the instance started before the instance was `ready`.

I would like to know if where's any options I can use to avoid this error. If not, I think I have to wrap all redis commands with retry strategy.

My client code is

```
'use strict';

const uuid = require('node-uuid');
const Redis = require('ioredis');

const wait = function (ms) {
	return new Promise(resolve => {
		setTimeout(() => {
			return resolve();
		}, ms);
	});
};

const __main__ = async function () {
	const redis = new Redis({
		port: 9000,
		host: `10.211.55.6`,
		enableReadyCheck: true
	});

	while (true) {
		const key = uuid.v4();
		const value = uuid.v4();
		const result = await redis.set(key, value);
		console.log(`SET ${key}: ${value} => ${result}`);
		await wait(100);
	}
};

__main__().then(() => {
	console.log(`done`);
}).catch(error => {
	console.error(error);
});
```

Twemproxy config
```
alpha:
  listen: 10.211.55.6:9000
  hash: fnv1a_64
  # hash_tag: "{}"
  distribution: ketama
  auto_eject_hosts: true
  redis: true
  server_retry_timeout: 2000
  server_failure_limit: 1
  preconnect: true
  servers:
   - 10.211.55.6:9001:1 server01
   - 10.211.55.6:9002:1 server02
   - 10.211.55.6:9003:1 server03
   - 10.211.55.6:9004:1 server04
```
