### ISSUE TITLE
Fails to connect to redis, when running inside of docker container

### ISSUE THREAD

**Issue by MishUshakov** [luin/ioredis#763]
Hey, the library works like a charm, thanks a lot. My application is a microservice, which connects to a redis database, which is running inside of docker. However, I can not connect to redis, when my application is running inside of container. I can still connect to redis remotely via cli on other host and it clearly works. I can also run my application outside of docker (directly on my host machine) and it would still connect. But when I build and run the image, it says:

```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
```

I also tried to provision my application to docker swarm with compose file on the same network as redis

```yml
version: "3"
services:
  myapp:
    image: user/app:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - webnet

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data:/data"
    command: redis-server --appendonly yes
    networks:
      - webnet
      
networks:
  webnet:
```

But it still wouldn't connect

Here is the code, I use in my application:

```js
const redis = require('ioredis')
const appdb = new redis()

module.exports = { db }
```

Thank you in advance.

**Comment by luin** [comment]
Have you tried connecting to Redis via host "redis" (see https://docs.docker.com/compose/networking/)?

```javascript
const redis = require('ioredis')
const appdb = new redis({host: 'redis'})

module.exports = { db }
```

**Comment by MishUshakov** [comment]
Hey, @luin thanks for quick reply, I will try it and comment back in the issue in a second. Thank you

**Comment by MishUshakov** [comment]
Still fails, but now with this error:

```
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
```

**Comment by luin** [comment]
Will, that is a network problem and it should not be related to ioredis.

**Comment by MishUshakov** [comment]
Ok, then I will try to hack around on my docker machine. Thank you

**Comment by DOTA2mm** [comment]
Same problem for me, it's still exist I've tried all suggestions above. Who can help me to resolve this, please.

**Comment by DOTA2mm** [comment]
> Same problem for me, it's still exist I've tried all suggestions above. Who can help me to resolve this, please.

It's ok after I run `docker-compose build` then `docker-compose up`.

**Comment by portinos** [comment]
> @mishushakov Try delete the networks and replace redis section by:
> 
> ```yaml
> redis:
>     image: redis:latest
>     command: ["redis-server", "--bind", "redis", "--port", "6379"]
> ```
> 
> That works for me.

Hey! How about running redis without docker-compose? I mean, running only the image. I lift the redis container using `docker run --name redis.server -d -p 6379:6379 redis:latest` but I can't connect from Sails (Node.js) using **redis.server** as hostname; the response is **ENOTFOUND**. The docker container is the official: https://hub.docker.com/_/redis/

**Comment by shanurrahman** [comment]
> @mishushakov Try delete the networks and replace redis section by:
> 
> ```yaml
> redis:
>     image: redis:latest
>     command: ["redis-server", "--bind", "redis", "--port", "6379"]
> ```
> 
> That works for me.

You saved me tonight

**Comment by ravipamarthi-suuchi** [comment]
> > @mishushakov Try delete the networks and replace redis section by:
> > ```yaml
> > redis:
> >     image: redis:latest
> >     command: ["redis-server", "--bind", "redis", "--port", "6379"]
> > ```
> > 
> > 
> > That works for me.
> 
> You saved me tonight

**Unfortunately did not work for me.** 
I deleted the docker networks. do i need to delete any other network, if any , please guide me. 
i still have the error: [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379

Below is my docker-compose.yml file
version: '3'
services:
  redis:
    image: 'redis'
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"
    networks:
      - app-tier
  apiserver:
    build: .
    ports:
     - "7001:7000"
    networks:
      - app-tier
    depends_on:
     - redis
networks:
  app-tier:
    driver: bridge

below is my app.js
const Redis = require('ioredis');
const redis = new Redis();
I changed the above to const redis = new Redis({host: 'redis'}); but i still get the error

package.json file references to ioredis, 
    "ioredis": "^4.0.2",

**Comment by armenr** [comment]
I'm having a similar issue, and I've tried it a few different ways as suggested here.

**Comment by shanurrahman** [comment]
Try using something like this, i dont see you using the port no to connect
to redis.
 redis: new Redis({
    port: 6379,
    host: process.env.REDIS_HOST,
    password: process.env.REDIS_PASS,
  }),

**Comment by shanurrahman** [comment]
Try using something like this, i dont see you using the port no to connect
to redis.
` redis: new Redis({
    port: 6379,
    host: process.env.REDIS_HOST, 
    password: process.env.REDIS_PASS,
  })`


in place of host you can simply use 'redis'
dont forget to provide the port number

**Comment by shamim-42** [comment]
> @mishushakov Try delete the networks and replace redis section by:
> 
> ```yaml
> redis:
>     image: redis:latest
>     command: ["redis-server", "--bind", "redis", "--port", "6379"]
> ```
> 
> That works for me.

After couple days of stuck today my project is running in your way. Thanks !

**Comment by mhtsharma948** [comment]
> @mishushakov Try delete the networks and replace redis section by:
> 
> ```yaml
> redis:
>     image: redis:latest
>     command: ["redis-server", "--bind", "redis", "--port", "6379"]
> ```
> 
> That works for me.

This still doesn't works for me, throwing this error.
`redis_1  | 1:M 21 Jul 2020 17:47:13.048 # Could not create server TCP listening socket redis:6380: Name or service not known`

**Comment by saefullohmaslul** [comment]
> @mishushakov Try delete the networks and replace redis section by:
> 
> ```yaml
> redis:
>     image: redis:latest
>     command: ["redis-server", "--bind", "redis", "--port", "6379"]
> ```
> 
> That works for me.

you save my life

**Comment by 103cuong** [comment]
The same issue, any solution for this problem? Thanks.
#### docker-compose
```yml
version: "3"

networks:
  dev_env_network:
    driver: bridge

services:
  redis:
    container_name: redis
    image: redis:6.0-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - dev_env_network
  auth-service:
    container_name: auth-service
    image: node:12
    working_dir: /app
    env_file: .env
    environment:
      - PG_DB=auth-service
    ports:
      - 50002:50002
    volumes:
      - ../auth-service:/app
      - ../auth-service/node_modules:/app/node_modules
    networks:
      - dev_env_network
    command: yarn start:dev
```
#### application
```ts
import Redis from 'ioredis';
const redis = new Redis({
    host: 'redis',
    port: 6379,
  });
```
#### error
```sh
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

**Comment by erinoggz** [comment]
```
Solution
const client = redis.createClient({
    host: 'redis-server',
    port: 6379
})

Then rebuild ur docker with => docker-compose up --build 
```

**Comment by DrPep** [comment]
For those who still have an issue here, my docker compose setup is/was configured with a bridged network setup. Adding Redis to the bridged network was required to allow it's network peers to connect:

```
redis:
  container_name: redis
  image: redis:latest
  command: ["redis-server", "--bind", "redis", "--port", "6379"]
  networks:
    - mynetwork 

networks:
  mynetwork:
    driver: bridge
```

Then connecting from my docker-hosted Node app with:

```
import redis from "ioredis"
const appdb = new redis({ host: "redis", port: 6379 })
```

If you want to then bind from the host machine, add in the requisite docker-compose port binding to the `redis` config block:
```
ports:
  - 6379:6379
```
HTH!

**Comment by khamphou** [comment]
> @mishushakov Try delete the networks and replace redis section by:
> 
> ```yaml
> redis:
>     image: redis:latest
>     command: ["redis-server", "--bind", "redis", "--port", "6379"]
> ```
> 
> That works for me.



> > @mishushakov Try delete the networks and replace redis section by:
> > ```yaml
> > redis:
> >     image: redis:latest
> >     command: ["redis-server", "--bind", "redis", "--port", "6379"]
> > ```
> > 
> > 
> > That works for me.
> 
> you save my life

You saved my life too, spent many days to fix this nodejs code, and it looks like it was caused by the docker used in my QNAP container station.

 redis:
    image: redis:latest
    container_name: devredisjs
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 32700
    ports:
      - "32700:6379"
    volumes:
      - /share/Smart-Web/cache/redis:/data
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

**Comment by houstondapaz** [comment]
I fix this issue changing the `redis.conf`, by default it use `127.0.0.1`, changing to `0.0.0.0` works like a charm
 Just create an redis.conf file with this content:
```
# bind 127.0.0.1
bind 0.0.0.0
```
and send this file to container, using compose just link this volume
```
volumes:
  - /path/to/redis.conf:/tmp/redis.conf
```

**Comment by AA25** [comment]
For others whose issue wasn't fixed by the above, this stackoverflow answer worked for me https://stackoverflow.com/a/58891367

If you're trying to connect from an app running in a container e.g. node app to redis running in a docker container, then the host string you set in your node app will need to be the name of your redis service name.

**Comment by sharkdevs** [comment]
> ```
> Solution
> const client = redis.createClient({
>     host: 'redis-server',
>     port: 6379
> })
> 
> Then rebuild ur docker with => docker-compose up --build 
> ```

you are a saviour indeed

**Comment by frankgo81** [comment]
Solution
const client = redis.createClient({
    host: 'redis-server',
    port: 6379
})

Then rebuild ur docker with => docker-compose up --build 

Works!! thanks

**Comment by ahmad2smile** [comment]
Following seems related: https://github.com/StackExchange/StackExchange.Redis/issues/1002

**Comment by renatoam** [comment]
I don't know why, neither if I'm doing something wrong, but what worked for me was put the same name to `REDIS_HOST` and the `container_name`, in compose file.

`docker-compose.yaml`

```yaml
cache:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: ${REDIS_HOST} # getting name from .env file
```

`redis.ts`

```typescript
export const redis = new Redis({
  port: Number(process.env.REDIS_PORT) || 6379,
  host: process.env.REDIS_HOST, // getting the same name from .env file
  password: process.env.REDIS_PASSWORD
});
```

**Comment by sbk2k1** [comment]
Update: <strong>26 July 2023</strong>

My docker-compose looks like this

```
redis:
    image: redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my-network
    ports:
      - 6379:6379
```

Passing the REDIS url through the Backend like this

```
environment:
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - API_INTERVAL=${API_INTERVAL}
      - REDIS_URL=${REDIS_URL}
```

.env looks like this

```
REDIS_URL='redis://redis:6379'
```

and using it in Node

```
var client = redis.createClient({url: process.env.REDIS_URL});
```

**Comment by myoshizumi** [comment]
> ```yaml
> redis:
>     image: redis:latest
>     command: ["redis-server", "--bind", "redis", "--port", "6379"]
> ```

Thank you so much for sharing your knowledge! You save my day🙏🏻🙏🏻🙏🏻

**Comment by anushree0809** [comment]
I am getting the same error, but none of the above steps are working, please help!
docker-compose.dev.yaml file
`version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - talawa-network

  redis-stack-server:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data/redis
    networks:
      - talawa-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - talawa-network

  talawa-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
      - redis-stack-server
      - minio
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  mongodb-data:
  redis-data:
  caddy_data:
  caddy_config:
  minio-data:

networks:
  talawa-network:
    driver: bridge
`
my .env file:
`REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=12345678`

I am setting up a repository in my local system and followed the steps mentioned.

**Comment by Malith-Rukshan** [comment]
> redis-stack-server:
> image: redis/redis-stack-server:latest
> ports:
> - 6379:6379
> volumes:
> - redis-data:/data/redis
> networks:
> - talawa-network

Update  `redis-stack-server` as follows :

```yaml
redis-stack-server:
    image: redis/redis-stack-server:latest
    command: ["redis-server", "--bind", "redis-stack-server", "--port", "6379"]
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data/redis
    networks:
      - talawa-network
```
