### ISSUE TITLE
local dev environment for sentinel

### ISSUE THREAD

**Issue by Karnich** [luin/ioredis#881]
Hi

How do you test / develop with sentinel locally? I really want a docker-compose setup to make it easy for the developers to get going without needing to install redis locally. But i have not found a way to get it working locally with ioredis and docker-compose. 

Anyone that can help mere?

right now my docker-compose looks like this: 
```
version: '3'

services:
    redis_master:
        image: redis:5.0.3-alpine
        ports:
            - "6379:6379"

    redis_slave:
        image: redis:5.0.3-alpine
        command: redis-server --slaveof redis_master 6379
        depends_on:
            - redis_master

    sentinel:
        build: ./sentinel
        image: redis-sentinel
        environment:
            - MASTER_NAME=mymaster
            - QUORUM=1
            - MASTER=redis_master
        depends_on:
            - redis_master
        ports:
            - "26379:26379"
```

Seems to work but when i try to connect to it on localhost:26379 i get this: 
```
error { Error: connect ENETUNREACH 192.168.192.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.192.2',
  port: 6379 }
```

Not really sure why it gets port 6379? shouldnt it be a sentinel port 26379?

**Comment by Karnich** [comment]
solved with 
```
docker run --name redis -p 6379:6379 -d redis
docker run --name redis-sentinel -e REDIS_MASTER_HOST=localhost -p 26379:26379 bitnami/redis-sentinel:latest
```

**Comment by iganev0886** [comment]
Here's a docker compose

```
version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net

  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel
    environment:
      - REDIS_MASTER_HOST=localhost
      - REDIS_MASTER_PORT_NUMBER=6379
    ports:
      - "26379:26379"
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
```
